networks:
  app-network:

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: RareBooks    
    ports:
      - "5433:5432"
    networks:
      - app-network
  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
        - backend
        - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - app-network

  backend:
    image: ${DOCKER_REGISTRY-}rarebooksservice-backend
    build:
      context: .
      dockerfile: RareBooksService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=RareBooks;Username=postgres;Password=123456
    depends_on:
      - postgres
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    image: rarebooksservice-frontend
    build:
      context: ./rarebooksservice.frontend.v3
      dockerfile: Dockerfile
    networks:
      - app-network 
